FROM java:8-jdk-alpine

COPY target/hello-world-kubernetes-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch hello-world-kubernetes-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","hello-world-kubernetes-0.0.1-SNAPSHOT.jar"]